name: "Release"

on:
  push:
    branches: ["master"]

jobs:
  release:
    name: build new release
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/release-github-actions@v6
        with:
          CREATE_MINOR_VERSION_TAG: false
          COMMIT_NAME: "5eqn"
          COMMIT_EMAIL: "491100866@qq.com"
